# Generated by Django 5.0 on 2024-03-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, choices=[('w', 'Wheat beer'), ('l', 'Lager'), ('p', 'Pilsner'), ('i', 'IPA'), ('a', 'ALE'), ('s', 'Stout'), ('b', 'Bock')], help_text='Chose your type of beer!', max_length=1, null=True)),
                ('country_name', models.CharField(help_text='Enter name of a beer type', max_length=200)),
                ('color', models.CharField(choices=[('l', 'Light / Straw'), ('a', 'Amber'), ('c', 'Copper / Reddish-Brown'), ('b', 'Brown'), ('d', 'Black')], help_text='Choose your colour of beer!', max_length=1)),
                ('filtered', models.CharField(blank=True, choices=[('y', 'Filtered'), ('n', 'Unfiltered')], help_text='Choose filtered or unfiltered beer!', max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='beertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beer_stories.type'),
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
    ]
