# Generated by Django 5.0 on 2024-03-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_stories', '0002_types_types_alter_types_color_alter_types_filtered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Origin',
        ),
    ]
