# Generated by Django 5.0 on 2024-03-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_stories', '0002_type_alter_review_beertype_delete_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='types',
            field=models.CharField(blank=True, choices=[('Wheat beer', 'Wheat beer'), ('Pilsner', 'Pilsner'), ('IPA', 'IPA'), ('ALE', 'ALE'), ('Stout', 'Stout'), ('Bock', 'Bock'), ('Lager', 'Lager')], help_text='Chose your type of beer!', max_length=10, null=True),
        ),
    ]
